-- ============================================================================
-- SCRIPT DE DEFINIÇÃO DE SCHEMA RELACIONAL (POSTGRESQL 14+)
-- SISTEMA GENÉRICO DE GESTÃO EMPRESARIAL (ERP / OLTP)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. EXTENSÕES, FUNÇÕES E TRIGGERS
-- ----------------------------------------------------------------------------

-- Extensão nativa para geração de identificadores universais únicos (UUIDv4)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Função genérica para atualização automática de timestamp de alteração
-- Responsabilidade única: atualizar updated_at para a data e hora correntes
CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 2. TIPOS E ENUMS
-- ----------------------------------------------------------------------------

-- Papéis de acesso de usuários do sistema
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_usuario_perfil') THEN
        CREATE TYPE enum_usuario_perfil AS ENUM ('administrador', 'operador', 'vendedor', 'consulta');
    END IF;
END $$;

-- Ciclo de vida transacional de pedidos
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_pedido_status') THEN
        CREATE TYPE enum_pedido_status AS ENUM ('rascunho', 'pendente', 'aprovado', 'faturado', 'cancelado');
    END IF;
END $$;

-- ----------------------------------------------------------------------------
-- 3. TABELAS, CHAVES E CONSTRAINTS
-- ----------------------------------------------------------------------------

-- Tabela de usuários para autenticação e auditoria
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome_completo VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL, -- Armazena hashes seguros (ex: bcrypt, argon2), nunca senha plana
    perfil enum_usuario_perfil NOT NULL DEFAULT 'operador',
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT chk_usuarios_email_valido CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT chk_usuarios_senha_hash_tamanho CHECK (length(senha_hash) >= 60)
);

-- Tabela de clientes e parceiros comerciais
CREATE TABLE IF NOT EXISTS clientes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    documento_fiscal VARCHAR(32) NOT NULL, -- CPF ou CNPJ normalizado (somente dígitos)
    razao_social_nome VARCHAR(200) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(20),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_clientes_documento_fiscal UNIQUE (documento_fiscal),
    CONSTRAINT uq_clientes_email UNIQUE (email)
);

-- Tabela de categorias de produtos para classificação hierárquica normalizada
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    categoria_pai_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categorias_nome UNIQUE (nome),
    CONSTRAINT fk_categorias_categoria_pai FOREIGN KEY (categoria_pai_id) 
        REFERENCES categorias(id) ON DELETE RESTRICT
);

-- Tabela de produtos e inventário
CREATE TABLE IF NOT EXISTS produtos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    categoria_id BIGINT NOT NULL,
    codigo_sku VARCHAR(64) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    preco_unitario NUMERIC(15, 2) NOT NULL,
    estoque_atual NUMERIC(12, 3) NOT NULL DEFAULT 0.000,
    estoque_minimo NUMERIC(12, 3) NOT NULL DEFAULT 0.000,
    -- JSONB justificado: atributos dinâmicos e variáveis por categoria (ex.: cor, voltagem, peso, dimensões)
    especificacoes_tecnicas JSONB NOT NULL DEFAULT '{}'::jsonb,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_produtos_sku UNIQUE (codigo_sku),
    CONSTRAINT fk_produtos_categoria FOREIGN KEY (categoria_id) 
        REFERENCES categorias(id) ON DELETE RESTRICT,
    CONSTRAINT chk_produtos_preco_positivo CHECK (preco_unitario >= 0),
    CONSTRAINT chk_produtos_estoque_atual_valido CHECK (estoque_atual >= 0),
    CONSTRAINT chk_produtos_estoque_minimo_valido CHECK (estoque_minimo >= 0)
);

-- Tabela mestre de pedidos transacionais
CREATE TABLE IF NOT EXISTS pedidos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cliente_id UUID NOT NULL,
    vendedor_id UUID NOT NULL,
    status enum_pedido_status NOT NULL DEFAULT 'rascunho',
    -- Justificativa de desnormalização: valor_total armazena o consolidado calculado para otimização de leitura em relatórios OLTP
    valor_total NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    observacoes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) 
        REFERENCES clientes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pedidos_vendedor FOREIGN KEY (vendedor_id) 
        REFERENCES usuarios(id) ON DELETE RESTRICT,
    CONSTRAINT chk_pedidos_valor_total_positivo CHECK (valor_total >= 0)
);

-- Tabela de detalhes/itens do pedido (relacionamento N:N entre pedidos e produtos)
CREATE TABLE IF NOT EXISTS pedido_itens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pedido_id UUID NOT NULL,
    produto_id UUID NOT NULL,
    quantidade NUMERIC(12, 3) NOT NULL,
    -- Snapshot histórico do preço praticado no instante do pedido (imutabilidade contábil)
    preco_unitario_aplicado NUMERIC(15, 2) NOT NULL,
    -- Coluna gerada deterministicamente pelo banco de dados para garantir integridade matemática
    subtotal NUMERIC(15, 2) GENERATED ALWAYS AS (quantidade * preco_unitario_aplicado) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_pedido_itens_pedido_produto UNIQUE (pedido_id, produto_id),
    CONSTRAINT fk_pedido_itens_pedido FOREIGN KEY (pedido_id) 
        REFERENCES pedidos(id) ON DELETE CASCADE,
    CONSTRAINT fk_pedido_itens_produto FOREIGN KEY (produto_id) 
        REFERENCES produtos(id) ON DELETE RESTRICT,
    CONSTRAINT chk_pedido_itens_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT chk_pedido_itens_preco_positivo CHECK (preco_unitario_aplicado >= 0)
);

-- Triggers de atualização automática de 'updated_at'
CREATE OR REPLACE TRIGGER trg_usuarios_updated_at
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE OR REPLACE TRIGGER trg_clientes_updated_at
    BEFORE UPDATE ON clientes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE OR REPLACE TRIGGER trg_categorias_updated_at
    BEFORE UPDATE ON categorias
    FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE OR REPLACE TRIGGER trg_produtos_updated_at
    BEFORE UPDATE ON produtos
    FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

CREATE OR REPLACE TRIGGER trg_pedidos_updated_at
    BEFORE UPDATE ON pedidos
    FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

-- ----------------------------------------------------------------------------
-- 4. ÍNDICES
-- ----------------------------------------------------------------------------

-- Índices em chaves estrangeiras para otimizar operações de JOIN
CREATE INDEX IF NOT EXISTS idx_categorias_categoria_pai_id ON categorias(categoria_pai_id);
CREATE INDEX IF NOT EXISTS idx_produtos_categoria_id ON produtos(categoria_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_cliente_id ON pedidos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_vendedor_id ON pedidos(vendedor_id);
CREATE INDEX IF NOT EXISTS idx_pedido_itens_pedido_id ON pedido_itens(pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedido_itens_produto_id ON pedido_itens(produto_id);

-- Índices compostos e parciais para filtros frequentes no sistema OLTP
CREATE INDEX IF NOT EXISTS idx_pedidos_status_created_at ON pedidos(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_produtos_ativo_sku ON produtos(ativo, codigo_sku);

-- Índice GIN para busca e filtros de alta performance nos atributos variáveis em JSONB
CREATE INDEX IF NOT EXISTS idx_produtos_especificacoes_gin ON produtos USING gin (especificacoes_tecnicas jsonb_path_ops);

-- ----------------------------------------------------------------------------
-- 5. COMENTÁRIOS EXPLICATIVOS DO SCHEMA (DOCUMENTAÇÃO INTERNA DO BANCO)
-- ----------------------------------------------------------------------------

COMMENT ON TABLE usuarios IS 'Contas de acesso e operadores do sistema transacional';
COMMENT ON COLUMN usuarios.senha_hash IS 'Armazena hash criptográfico seguro gerado pela aplicação';

COMMENT ON TABLE clientes IS 'Entidades consumidoras e contatos comerciais';
COMMENT ON COLUMN clientes.documento_fiscal IS 'Registro de CPF ou CNPJ formatado sem pontuação';

COMMENT ON TABLE categorias IS 'Classificação taxonômica de itens com suporte a auto-relacionamento';

COMMENT ON TABLE produtos IS 'Itens mantidos em catálogo com suporte a controle de saldo em estoque';
COMMENT ON COLUMN produtos.especificacoes_tecnicas IS 'Metadados semiestruturados indexados via GIN para evitar tabelas EAV';

COMMENT ON TABLE pedidos IS 'Cabeçalho da transação comercial de venda';
COMMENT ON COLUMN pedidos.valor_total IS 'Total consolidado da venda mantido para agilidade em leituras de listas e relatórios';

COMMENT ON TABLE pedido_itens IS 'Linhas de detalhe de produtos contidos em um pedido específico';
COMMENT ON COLUMN pedido_itens.subtotal IS 'Coluna calculada e gravada em disco automaticamente pelo PostgreSQL';

-- ----------------------------------------------------------------------------
-- 6. INSERTS DE EXEMPLO (ILUSTRAÇÃO DO PADRÃO DE DADOS ESPERADO)
-- ----------------------------------------------------------------------------

-- Exemplo de usuário administrador com hash de senha simulado
INSERT INTO usuarios (id, nome_completo, email, senha_hash, perfil, ativo)
VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Administrador do Sistema',
    'admin@empresa.com.br',
    '$2a$12$e8p4F44b9Gk2R05WzQ52ye7d0nQx9kS.x4m1N2y3k6vG8iJ1pZ2bC',
    'administrador',
    TRUE
) ON CONFLICT (email) DO NOTHING;

-- Exemplo de cliente corporativo
INSERT INTO clientes (id, documento_fiscal, razao_social_nome, email, telefone, ativo)
VALUES (
    'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    '12345678000195',
    'Tecnologia e Inovação Ltda',
    'financeiro@tecnologia.com.br',
    '+5511999998888',
    TRUE
) ON CONFLICT (documento_fiscal) DO NOTHING;

-- Exemplo de categoria pai e subcategoria
INSERT INTO categorias (id, nome, descricao, categoria_pai_id)
VALUES 
    (1, 'Hardware', 'Componentes e peças de computadores', NULL),
    (2, 'Armazenamento', 'Dispositivos de armazenamento e discos rápidos', 1)
ON CONFLICT (id) DO NOTHING;

-- Sincronização do sequenciador de categorias após inserção manual de IDs
SELECT setval(pg_get_serial_sequence('categorias', 'id'), coalesce(max(id), 1)) FROM categorias;

-- Exemplo de produto com metadados em JSONB
INSERT INTO produtos (
    id,
    categoria_id,
    codigo_sku,
    nome,
    descricao,
    preco_unitario,
    estoque_atual,
    estoque_minimo,
    especificacoes_tecnicas,
    ativo
)
VALUES (
    'c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    2,
    'SSD-NVME-1TB-001',
    'SSD NVMe M.2 1TB Leitura 3500MB/s',
    'Unidade de armazenamento de alto desempenho para servidores e estações de trabalho',
    499.90,
    50.000,
    10.000,
    '{"interface": "PCIe 3.0 x4", "fator_forma": "M.2 2280", "leitura_maxima_mb": 3500, "garantia_meses": 36}'::jsonb,
    TRUE
) ON CONFLICT (codigo_sku) DO NOTHING;

-- Exemplo de cabeçalho de pedido
INSERT INTO pedidos (
    id,
    cliente_id,
    vendedor_id,
    status,
    valor_total,
    observacoes
)
VALUES (
    'd3eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
    'b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'aprovado',
    999.80,
    'Pedido corporativo faturado com entrega prioritária'
) ON CONFLICT (id) DO NOTHING;

-- Exemplo de item pertencente ao pedido
INSERT INTO pedido_itens (
    id,
    pedido_id,
    produto_id,
    quantidade,
    preco_unitario_aplicado
)
VALUES (
    'e4eebc99-9c0b-4ef8-bb6d-6bb9bd380a55',
    'd3eebc99-9c0b-4ef8-bb6d-6bb9bd380a44',
    'c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    2.000,
    499.90
) ON CONFLICT (pedido_id, produto_id) DO NOTHING;
